default: &default
  adapter: postgresql
  encoding: utf8

development:
  <<: *default
  database: loan_sharer_development

test:
  <<: *default
  database: loan_sharer_test

production:
  <<: *default
  database: loan_sharer_production
  username: loan_sharer
  password: <%= ENV['DUMMY_EQUITY_DATABASE_PASSWORD'] %>
